//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.DataAccess
{
    using System;
    
    public enum CategoryType : int
    {
        Initial = 0,
        Income = 1,
        Expense = 2
    }
}
