//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered amount is invalid.
        /// </summary>
        internal static string ADD_AMOUNT_INVALID {
            get {
                return ResourceManager.GetString("ADD_AMOUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed characters are 50.
        /// </summary>
        internal static string ADD_LOCATION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ADD_LOCATION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name.
        /// </summary>
        internal static string ADD_NAME_MANDATORY {
            get {
                return ResourceManager.GetString("ADD_NAME_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed characters are 30.
        /// </summary>
        internal static string ADD_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ADD_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed characters are 50.
        /// </summary>
        internal static string ADD_NOTE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ADD_NOTE_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type must be selected.
        /// </summary>
        internal static string ADD_TYPE_MANDATORY {
            get {
                return ResourceManager.GetString("ADD_TYPE_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseTracker.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Category.
        /// </summary>
        internal static string CAT_ADD_NEW {
            get {
                return ResourceManager.GetString("CAT_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category should be inserted before you proceed.
        /// </summary>
        internal static string CAT_COUNT {
            get {
                return ResourceManager.GetString("CAT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rs..
        /// </summary>
        internal static string CURRENCY_PREFIX {
            get {
                return ResourceManager.GetString("CURRENCY_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Accounts.
        /// </summary>
        internal static string DASHBOARD_ALL_ACCOUNTS {
            get {
                return ResourceManager.GetString("DASHBOARD_ALL_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        internal static string DASHBOARD_NO_RECORDS {
            get {
                return ResourceManager.GetString("DASHBOARD_NO_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string DASHBOARD_SHOW_ALL {
            get {
                return ResourceManager.GetString("DASHBOARD_SHOW_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DASHBOARD_TITLE {
            get {
                return ResourceManager.GetString("DASHBOARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the entire row to delete the record.
        /// </summary>
        internal static string DELETE_REC_MSG {
            get {
                return ResourceManager.GetString("DELETE_REC_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        internal static string DELETE_REC_TITLE {
            get {
                return ResourceManager.GetString("DELETE_REC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Event.
        /// </summary>
        internal static string EVT_ADD_NEW {
            get {
                return ResourceManager.GetString("EVT_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string EXPENSE_TYPE {
            get {
                return ResourceManager.GetString("EXPENSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Financial Account.
        /// </summary>
        internal static string FA_ADD_NEW {
            get {
                return ResourceManager.GetString("FA_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to create a financial account before you proceeed.
        /// </summary>
        internal static string FA_COUNT {
            get {
                return ResourceManager.GetString("FA_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string INCOME_TYPE {
            get {
                return ResourceManager.GetString("INCOME_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LOGIN_FAILED_CAPTION {
            get {
                return ResourceManager.GetString("LOGIN_FAILED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid credentials..
        /// </summary>
        internal static string LOGIN_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("LOGIN_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your windows credentials to continue..
        /// </summary>
        internal static string LOGIN_MESSAGE {
            get {
                return ResourceManager.GetString("LOGIN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Tracker.
        /// </summary>
        internal static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        internal static string REPORT_ALL_CATEGORIES {
            get {
                return ResourceManager.GetString("REPORT_ALL_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        internal static string REPORT_ALL_EVENTS {
            get {
                return ResourceManager.GetString("REPORT_ALL_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Payees.
        /// </summary>
        internal static string REPORT_ALL_PAYEES {
            get {
                return ResourceManager.GetString("REPORT_ALL_PAYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction can&apos;t be done.
        /// </summary>
        internal static string TNX_NA {
            get {
                return ResourceManager.GetString("TNX_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds to make the Transfer.
        /// </summary>
        internal static string TRANSFER_INSUFFICIENT_FUNDS {
            get {
                return ResourceManager.GetString("TRANSFER_INSUFFICIENT_FUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount to transfer.
        /// </summary>
        internal static string TRANSFER_INVALID_AMOUNT {
            get {
                return ResourceManager.GetString("TRANSFER_INVALID_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make a Fund Transfer, you must have at least two Financial Accounts..
        /// </summary>
        internal static string TRANSFER_NA_MSG {
            get {
                return ResourceManager.GetString("TRANSFER_NA_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer not available.
        /// </summary>
        internal static string TRANSFER_NA_TITLE {
            get {
                return ResourceManager.GetString("TRANSFER_NA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a different account other than the from account.
        /// </summary>
        internal static string TRANSFER_TO_SAME_ACCOUNT {
            get {
                return ResourceManager.GetString("TRANSFER_TO_SAME_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Transfer.
        /// </summary>
        internal static string TRANSFER_VIEW_TITLE {
            get {
                return ResourceManager.GetString("TRANSFER_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Transaction.
        /// </summary>
        internal static string TXN_ADD_NEW {
            get {
                return ResourceManager.GetString("TXN_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transaction.
        /// </summary>
        internal static string TXN_EDIT {
            get {
                return ResourceManager.GetString("TXN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t make expenses more than your account balance.
        /// </summary>
        internal static string TXN_ERR {
            get {
                return ResourceManager.GetString("TXN_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly View.
        /// </summary>
        internal static string WEEKLY_VIEW_TITLE {
            get {
                return ResourceManager.GetString("WEEKLY_VIEW_TITLE", resourceCulture);
            }
        }
    }
}
